-- HD2-Addon: mods/alomare/skip_intro_animation
-- Impatient Diver by Alomare.
--
-- Skips ship sequences. Each is set in Mod Options Menu (escape menu > MODS) to Off, Manual (spacebar, plus an
-- optional Mod Bindings Menu binding) or Automatic; without that mod each is Automatic:
--   Log-in ship intro    ship_intro, then ship_bridge_intro
--   Cryo pod transition  ship_teleporter_arrival (the game itself places the Helldiver at the pod exit)
--   FTL transition       ship_planet_departure, ship_planet_arrival and ship_teleporter_network_join
--                        (joining a lobby), with the FTL screen fades held clear
--   Hellpod to loadout   the local Helldiver's seat transition into its hellpod, then the Hellpod briefing's intro
--                        wait (experimental); the briefing, loadout and launch are untouched
-- Every skip is a fast-forward: each scene's phases wait on timers, and the mod moves the running phase's
-- timer on so the game's own update changes phase, with everything that phase change normally does. The hellpod
-- entry is the same idea: the seat transition waits on a deadline per step, which the mod moves to now.
-- Loading waits are never skipped. (Version 1 ended the log-in intro through the game's interrupt, whose
-- abort path left cinematic state behind that crashed the next hellpod launch.)
--
-- Galactic Map Quick Exit (always on): Escape, or the Mod Bindings Menu key "Close galactic map", on the galactic map
-- sets the map presenter's own close request, so the game's presenter manager closes it (and pops its screen) that
-- frame, from any zoom level.
--
-- Everything native is found in game.dll by code signatures (first at this build's addresses, else by a search
-- of its executable sections spread over frames, where a signature must match exactly once), timer waits and
-- structure offsets are read from the matched code, and scene ids come from the game's own id-to-name table.
-- Anything not found, or found more than once, disables only what depends on it, and that sequence plays normally.
-- Memory is read and written with ReadProcessMemory / WriteProcessMemory on the game's own process, which fail
-- instead of crashing.
-- Status: %LOCALAPPDATA%\CowboyBingus\Helldivers2\Logs\ImpatientDiver_STATUS.log (first line = verdict).
if rawget(_G, 'ImpatientDiver') then return end

local ffi = require('ffi')

local M = {version = '5', frames = 0, errors = 0}
rawset(_G, 'ImpatientDiver', M)

local S = rawget(_G, 'stingray')
local loader = rawget(_G, 'CowboyBingusModLoader')

---------------------------------------------------------------------------------------
-- The game's code (research notes: NOTES.md beside this script)

-- BEGIN SIGNATURES (generated by research/signatures.py; game.dll build 25480438 addresses)
local SIGS = {
    {name = 'interrupt_site', rva = 0xad6ca2, optional = true, text = '48 8B 0D ?? ?? ?? ?? 39 91 ?? ?? ?? ?? 0F 84 ?? ?? ?? ?? 48 83 C4 30 5B E9 ?? ?? ?? ??',
     fields = {manager = {'rip', {3}, {7}}, current = {'u32', {9}}}},
    {name = 't13p2', rva = 0x1178030, optional = true, text = '48 8B 05 ?? ?? ?? ?? 49 8B 88 ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 ?? 0F 82 ?? ?? ?? ?? F3 0F 10 05 ?? ?? ?? ??',
     fields = {clock = {'rip', {3}, {7}}, t13p2_stamp = {'u32', {10}}, t13p2_wait = {'u32', {17}}, clock_now = {'u8', {24}}}},
    {name = 't13p3', rva = 0x1177f9b, optional = true, text = '48 8B 8A ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 18 0F 82 ?? ?? ?? ?? C7 42 04 FF FF FF FF 33 FF',
     fields = {t13p3_stamp = {'u32', {3}}, t13p3_wait = {'u32', {10}}}},
    {name = 't13p4', rva = 0x1177ec4, optional = true, text = '49 8B 88 ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 18 0F 82 ?? ?? ?? ?? 48 8B 1D ?? ?? ?? ??',
     fields = {t13p4_stamp = {'u32', {3}}, t13p4_wait = {'u32', {10}}}},
    {name = 't12p3', rva = 0x117df3d, optional = true, text = '48 8B 8A ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 18 0F 82 ?? ?? ?? ?? BA 0B 00 00 00',
     fields = {t12p3_stamp = {'u32', {3}}, t12p3_wait = {'u32', {10}}}},
    {name = 't11p2', rva = 0x117dee2, optional = true, text = '48 8B 81 ?? ?? ?? ?? 48 05 ?? ?? ?? ?? 48 39 42 18 0F 82 ?? ?? ?? ?? BA 03 00 00 00',
     fields = {t11p2_stamp = {'u32', {3}}, t11p2_wait = {'u32', {9}}}},
    {name = 't15p3', rva = 0x1179efb, optional = true, text = '48 8B 81 ?? ?? ?? ?? 48 05 ?? ?? ?? ?? 49 39 40 18 0F 82 ?? ?? ?? ?? E8 ?? ?? ?? ?? 84 C0 0F 84 ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {t15p3_stamp = {'u32', {3}}, t15p3_wait = {'u32', {9}}}},
    {name = 't7p1', rva = 0x117dbb1, optional = true, text = '48 8B 81 ?? ?? ?? ?? 48 05 ?? ?? ?? ?? 48 39 42 18 0F 82 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 80 78 01 00 0F 84 ?? ?? ?? ?? BA 03 00 00 00',
     fields = {t7p1_stamp = {'u32', {3}}, t7p1_wait = {'u32', {9}}}},
    {name = 't7p2', rva = 0x117db78, optional = true, text = '48 8B 81 ?? ?? ?? ?? 48 05 ?? ?? ?? ?? 48 39 42 18 72 ?? 48 8B 81 D0 00 00 00 A8 02 75 ?? 48 83 C8 02 48 89 81 D0 00 00 00 E8 ?? ?? ?? ?? 48 8B 4B 08 48 8B 15 ?? ?? ?? ?? 48 8B 81 ?? ?? ?? ?? 48 05 C0 C6 2D 00',
     fields = {t7p2_stamp = {'u32', {3, 60}}, t7p2_wait = {'u32', {9}}}},
    {name = 't3_2s', rva = 0x116d7d8, optional = true, text = '48 8B 8A ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 18 0F 82 ?? ?? ?? ?? BA 03 00 00 00 48 8B CB 48 83 C4 20 5B E9 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 8B 8A ?? ?? ?? ?? 48 81 C1 D0 12 13 00',
     fields = {t3_2s_stamp = {'u32', {3, 52}}, t3_2s_wait = {'u32', {10}}}},
    {name = 't3_125', rva = 0x116d809, optional = true, text = '48 8B 8A ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 18 0F 82 ?? ?? ?? ?? 43 8B 8C 81 A8 DA 16 01',
     fields = {t3_125_stamp = {'u32', {3}}, t3_125_wait = {'u32', {10}}}},
    {name = 't3_175', rva = 0x116d8bb, optional = true, text = '48 8B 8A ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 18 0F 82 ?? ?? ?? ?? 43 8B 8C 81 D8 DA 16 01',
     fields = {t3_175_stamp = {'u32', {3}}, t3_175_wait = {'u32', {10}}}},
    {name = 't3_25', rva = 0x116d92f, optional = true, text = '48 8B 8A ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? E9 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 8B 8A ?? ?? ?? ?? 48 81 C1 40 42 0F 00 48 39 48 18 0F 82 ?? ?? ?? ?? BA 07 00 00 00',
     fields = {t3_25_stamp = {'u32', {3, 29}}, t3_25_wait = {'u32', {10}}}},
    {name = 't3_1s', rva = 0x116d949, optional = true, text = '48 8B 8A ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 18 0F 82 ?? ?? ?? ?? BA 07 00 00 00',
     fields = {t3_1s_stamp = {'u32', {3}}, t3_1s_wait = {'u32', {10}}}},
    {name = 't3_15', rva = 0x116d97a, optional = true, text = '48 8B 8A ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 48 39 48 18 0F 82 ?? ?? ?? ?? BA 08 00 00 00',
     fields = {t3_15_stamp = {'u32', {3}}, t3_15_wait = {'u32', {10}}}},
    {name = 'game_state', rva = 0x11d5b23, optional = true, text = '48 8B 05 ?? ?? ?? ?? 83 B8 ?? ?? ?? ?? 04 74 ?? 32 C0',
     fields = {game = {'rip', {3}, {7}}, game_state = {'u32', {9}}}},
    {name = 'local_ref', rva = 0x4db76b, optional = true, text = '48 8B 05 ?? ?? ?? ?? 4C 8B F9 83 B8 ?? ?? ?? ?? 00 74 ?? 8B 90 ?? ?? ?? ?? 48 8D 4C 24 68 E8 ?? ?? ?? ??',
     fields = {players = {'rip', {3}, {7}}, local_active = {'u32', {12}}, avatar_ref = {'u32', {21}}, resolver = {'call', {31}, {35}}}},
    {name = 'ref_resolver', rva = 0xfd9ba4, optional = true, text = '4C 8B 1D ?? ?? ?? ?? 44 8B C2 4C 8B C9 81 FA FF 7F 00 00 75 ?? 8B 05 ?? ?? ?? ?? 89 01 48 8B C1 48 83 C4 08 C3 45 8B 93 ?? ?? ?? ?? 33 D2 48 89 5C 24 10 41 8B 9B ?? ?? ?? ?? 48 89 6C 24 18 41 0F AF D8 41 8D 6A FF 48 89 74 24 20 48 89 3C 24 45 85 D2 74 ?? 49 8B BB ?? ?? ?? ?? 41 8B B3 ?? ?? ?? ?? 66 0F 1F 84 00 00 00 00 00 8B C5 8D 0C 1A 48 23 C8 48 8D 04 CF 8B 0C CF 3B CE 74 ?? 41 3B C8 74 ?? FF C2 41 3B D2 72 ?? 33 C0 48 8B 3C 24 48 8B 74 24 20 48 8B 6C 24 18 48 8B 5C 24 10 44 39 00 75 ?? 8B 40 04 48 8D 04 40 48 8D 80 ?? ?? ?? ?? 49 8D 04 C3',
     fields = {entities = {'rip', {3}, {7}}, ent_capacity = {'u32', {40}}, ent_multiplier = {'u32', {54}}, ent_map = {'u32', {88}}, ent_empty = {'u32', {95}}, ent_ids = {'u32', {175}}}},
    {name = 'seaters', rva = 0x639846, optional = true, text = '8B 42 08 4D 8B F0 3B 05 ?? ?? ?? ?? 4C 8B 2D ?? ?? ?? ?? 74 ?? 45 8B 4D ?? 45 33 C0 45 8B 5D ?? 44 0F AF D8 41 8D 71 FF 45 85 C9 74 ?? 49 8B 5D ?? 41 8B 7D ?? 0F 1F 44 00 00 8B CE 43 8D 14 18 48 23 D1 8B 0C D3 4C 8D 14 D3 3B CF 0F 84 ?? ?? ?? ?? 3B C8 0F 84 ?? ?? ?? ?? 41 FF C0 45 3B C1 72 ?? BF FF FF FF FF 49 8B 45 ?? 44 8B E7 49 C1 E4 06',
     fields = {seaters = {'rip', {15}, {19}}, seat_capacity = {'u8', {24}}, seat_multiplier = {'u8', {31}}, seat_map = {'u8', {48}}, seat_empty = {'u8', {52}}, seat_records = {'u8', {106}}}},
    {name = 'seat_wait', rva = 0x639d57, optional = true, text = '44 38 6C 37 ?? 0F 84 ?? ?? ?? ?? F3 0F 10 35 ?? ?? ?? ?? 66 0F 1F 44 00 00 83 7C 37 ?? FF 0F 84 ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 8B 4C 37 ?? 48 39 48 ?? 0F 82 ?? ?? ?? ??',
     fields = {seat_moving = {'u8', {4}}, seat_target = {'u8', {28, 51}}, seat_clock = {'rip', {39}, {43}}, seat_deadline = {'u8', {47}}, seat_clock_now = {'u8', {28, 51}}}},
    {name = 'hellpods', rva = 0xadbaaf, optional = true, text = '48 8B 35 ?? ?? ?? ?? 33 FF 39 7E 08 76 ?? 0F 1F 00 48 8B 4C FE ?? 41 B8 03 00 00 00 8B 59 08',
     fields = {hellpods = {'rip', {3}, {7}}, pod_list = {'u8', {21}}}},
    {name = 'screen', rva = 0x1082ef0, optional = true, text = '48 8B 05 ?? ?? ?? ?? 48 8B 88 ?? ?? ?? ?? 83 B9 ?? ?? ?? ?? FF 0F 95 C0 C3',
     fields = {screen_stack = {'rip', {3}, {7}}, screen_slot = {'u32', {10}}, local_index = {'u32', {16}}}},
    {name = 'briefing_intro', rva = 0x146909f, optional = true, text = '83 BE ?? ?? ?? ?? 00 0F 84 ?? ?? ?? ?? F3 0F 10 86 ?? ?? ?? ?? F3 41 0F 5C C0 0F 2F F8 F3 0F 11 86 ?? ?? ?? ?? 0F 82 ?? ?? ?? ??',
     fields = {intro_phase = {'u32', {2}}, intro_timer = {'u32', {17, 33}}}},
    {name = 'fader', rva = 0x11d66c0, optional = true, text = '48 83 EC 38 48 8B 0D ?? ?? ?? ?? 33 D2 48 81 C1 ?? ?? ?? ?? 48 89 54 24 20 F2 0F 10 44 24 20 0F 28 D1 0F 57 C9 0F 2E D1 8B 81 ?? ?? ?? ?? 89 81 ?? ?? ?? ?? C7 81 ?? ?? ?? ?? 00 00 80 3F C7 81 98 07 00 00 00 00 00 80 F2 0F 11 81 88 07 00 00 89 91 90 07 00 00 F3 0F 11 91 ?? ?? ?? ??',
     fields = {fader = {'rip', {7}, {11}}, fader_offset = {'u32', {16}}, fader_alpha = {'u32', {42}}, fader_start = {'u32', {48}}, fader_target = {'u32', {54}}, fader_duration = {'u32', {90}}}},
    {name = 'names', rva = 0x117e950, optional = true, text = 'FF C9 83 F9 ?? 0F 87 ?? ?? ?? ?? 48 8D 15 ?? ?? ?? ?? 8B 8C 8A ?? ?? ?? ?? 48 03 CA FF E1',
     fields = {}},
    {name = 'presenters', rva = 0x662520, optional = true, text = '48 8B 0D ?? ?? ?? ?? 48 81 C1 ?? ?? ?? ?? 8B 41 ?? 83 E8 01 48 98 78 ?? 48 8D 0C 81 48 83 C1 ?? 83 39 0E 74 ?? 48 83 E9 04 48 83 E8 01 79 ?? C3 48 8B 0D ?? ?? ?? ??',
     fields = {ui = {'rip', {3}, {7}}, presenters = {'u32', {10}}, depth = {'u8', {16}}, stack = {'u8', {31}}}},
    {name = 'presenter_open', rva = 0x14c038e, optional = true, text = '83 79 ?? 00 74 ?? E8 ?? ?? ?? ?? 4C 8B C6',
     fields = {current_presenter = {'u8', {2}}, close = {'call', {7}, {11}}}},
    {name = 'presenter_update', rva = 0x14bf890, optional = true, text = '8B 16 48 8D 8B ?? ?? ?? ?? E8 ?? ?? ?? ?? 84 C0 74 ?? 48 8B CB E8 ?? ?? ?? ??',
     fields = {collection = {'u32', {5}}, check = {'call', {10}, {14}}, close = {'call', {22}, {26}}}},
    {name = 'hologram_request', rva = 0x14bdcbb, optional = true, text = '48 8B 81 90 00 00 00 0F B6 40 ?? C3 48 8B 81 ?? ?? ?? ?? 0F B6 40 ?? C3 48 8B 81 A0 00 00 00 0F B6 00 C3',
     fields = {holo_slot = {'u32', {15}}, close_flag = {'u8', {10, 22}}}},
}
-- END SIGNATURES

-- BEGIN SIGNATURE ENGINE (tools/sigscan.lua, written by research/signatures.py: edit it there)
-- Signature engine v1: finds game.dll code by signatures and reads values from the matched code.
-- Canonical copy: tools/sigscan.lua in the workspace. Each mod's research/signatures.py writes this block and the
-- mod's SIGS table into its script (tools/sigspec.py), so every mod carries the same engine.
--
-- A signature is {name, rva, text, fields, optional}: text is hex bytes with '??' wildcards; rva is where the
-- generating build had it. fields = {field = {kind, {offset...}, {next...}}}: kind 'u8' / 'u32' (a value inside the
-- matched code), 'rip' (a global: the target of a rip-relative operand) or 'call' (a function: the target of a rel32
-- call); offset = each occurrence's byte position in the pattern, next = the end of its instruction. Every occurrence
-- must agree, and a field shared by several signatures must agree across them.
--
--   local code = sigscan.new(SIGS, read, base, validate)  -- read(address, size) -> string or nil; base = game.dll
--                                                        -- base; validate (optional) = {name = function(rva) -> bool}:
--                                                        -- extra checks a match must pass (decoys don't count)
--   code:start()                                 -- tries each signature at its rva; true when all were there
--   code:step()                                  -- else: one chunk of the search per call; true when finished
--   code.found[name] (rva), code.missing[name] (reason), code.values[field], code.problems (list)
local sigscan = {}
do
    local CHUNK, OVERLAP = 0x400000, 256

    local function u16(b, o) return b:byte(o + 1) + 256 * b:byte(o + 2) end
    local function u32(b, o)
        local x1, x2, x3, x4 = b:byte(o + 1, o + 4)
        return x1 + 256 * x2 + 65536 * x3 + 16777216 * x4
    end
    local function i32(b, o)
        local v = u32(b, o)
        return v >= 2147483648 and v - 4294967296 or v
    end

    local function parse(sig)
        local bytes = {}
        for part in sig.text:gmatch('%S+') do bytes[#bytes + 1] = part ~= '??' and tonumber(part, 16) or false end
        local best_at, best_len, at, len = 1, 0, nil, 0  -- the longest run of fixed bytes is searched for
        for i = 1, #bytes + 1 do
            if bytes[i] then
                if not at then at, len = i, 0 end
                len = len + 1
                if len > best_len then best_at, best_len = at, len end
            else
                at = nil
            end
        end
        local anchor = {}
        for i = best_at, best_at + best_len - 1 do anchor[#anchor + 1] = string.char(bytes[i]) end
        sig.bytes, sig.anchor, sig.anchor_at = bytes, table.concat(anchor), best_at - 1
    end

    local function matches(blob, pos, sig)  -- pos: 1-based start in blob
        local bytes = sig.bytes
        if pos < 1 or pos + #bytes - 1 > #blob then return false end
        for i = 1, #bytes do
            local b = bytes[i]
            if b and blob:byte(pos + i - 1) ~= b then return false end
        end
        return true
    end

    local Scanner = {}
    Scanner.__index = Scanner

    function sigscan.new(sigs, read, base, validate)
        return setmetatable({sigs = sigs, read = read, base = base, validate = validate or {}, found = {}, missing = {},
                             moved = {}, values = {}, problems = {}, scan = nil, done = false}, Scanner)
    end

    function Scanner:valid(name, rva)
        local check = self.validate[name]
        if not check then return true end
        local ok, good = pcall(check, rva)
        return ok and good and true or false
    end

    -- game.dll's sections: {rva, size, exec}.
    function Scanner:load_sections()
        local read, base = self.read, self.base
        local dos = read(base, 0x40)
        local pe = dos and dos:sub(1, 2) == 'MZ' and u32(dos, 0x3c)
        local nt = pe and pe < 0x10000 and read(base + pe, 0x18)
        if not nt or nt:sub(1, 4) ~= 'PE\0\0' then return nil end
        local count, opt = u16(nt, 6), u16(nt, 20)
        local headers = count <= 96 and read(base + pe + 24 + opt, count * 40)
        if not headers then return nil end
        local sections = {}
        for i = 0, count - 1 do
            local size, rva, flags = u32(headers, i * 40 + 8), u32(headers, i * 40 + 12), u32(headers, i * 40 + 36)
            if size > 0 then
                sections[#sections + 1] = {rva = rva, size = size, exec = math.floor(flags / 0x20000000) % 2 == 1}
            end
        end
        return sections
    end

    function Scanner:in_section(rva, exec)
        for _, s in ipairs(self.sections) do
            if s.exec == exec and rva >= s.rva and rva + 8 <= s.rva + s.size then return true end
        end
        return false
    end

    -- Tries every signature at its rva and starts a search for the others. True when all were there (done), false
    -- when a search started, nil and a reason when game.dll is unreadable.
    function Scanner:start()
        self.sections = self:load_sections()
        if not self.sections then return nil, 'game.dll headers unreadable' end
        local wanted = {}
        for _, sig in ipairs(self.sigs) do
            parse(sig)
            local blob = self.read(self.base + sig.rva, #sig.bytes)
            if blob and matches(blob, 1, sig) and self:valid(sig.name, sig.rva) then
                self.found[sig.name] = sig.rva
            else
                wanted[#wanted + 1] = sig
            end
        end
        if #wanted == 0 then
            self:resolve()
            return true
        end
        local exec = {}
        for _, s in ipairs(self.sections) do if s.exec then exec[#exec + 1] = s end end
        self.scan = {sections = exec, section = 1, offset = 0, wanted = wanted, hits = {}}
        for _, sig in ipairs(wanted) do self.scan.hits[sig.name] = {} end
        return false
    end

    -- One chunk of the search (every match is collected: a signature must match exactly once). True when finished.
    function Scanner:step()
        local scan = self.scan
        if not scan then return true end
        local s = scan.sections[scan.section]
        if s then
            local from = scan.offset
            local size = math.min(CHUNK + OVERLAP, s.size - from)
            local pieces = {}
            local blob = self.read(self.base + s.rva + from, size)
            if blob then
                pieces[1] = {from, blob}
            else
                for off = from, from + size - 1, 0x10000 do  -- skip unreadable pages
                    local piece = self.read(self.base + s.rva + off, math.min(0x10000 + OVERLAP, s.size - off))
                    if piece then pieces[#pieces + 1] = {off, piece} end
                end
            end
            for _, piece in ipairs(pieces) do
                local piece_from, data = piece[1], piece[2]
                for _, sig in ipairs(scan.wanted) do
                    local init = 1
                    while true do
                        local at = data:find(sig.anchor, init, true)
                        if not at then break end
                        local start = at - sig.anchor_at
                        local offset = piece_from + start - 1
                        -- Matches starting in the overlap belong to the next chunk.
                        if offset >= from and offset < from + CHUNK and matches(data, start, sig)
                           and self:valid(sig.name, s.rva + offset) then
                            local hits = scan.hits[sig.name]
                            hits[#hits + 1] = s.rva + offset
                        end
                        init = at + 1
                    end
                end
            end
            scan.offset = from + CHUNK
            if scan.offset >= s.size then scan.section, scan.offset = scan.section + 1, 0 end
            if scan.sections[scan.section] then return false end
        end
        for _, sig in ipairs(scan.wanted) do
            local hits = scan.hits[sig.name]
            if #hits == 1 then
                self.found[sig.name] = hits[1]
                self.moved[#self.moved + 1] = sig.name
            else
                self.missing[sig.name] = #hits == 0 and 'not found' or ('found ' .. #hits .. ' times')
            end
        end
        self.scan = nil
        self:resolve()
        return true
    end

    -- A field's value from the matched code; nil and a reason if its occurrences disagree or it points nowhere.
    function Scanner:field_value(sig, rva, spec)
        local blob = self.read(self.base + rva, #sig.bytes)
        if not blob then return nil, 'unreadable' end
        local value
        for k, off in ipairs(spec[2]) do
            local v
            if spec[1] == 'u8' then v = blob:byte(off + 1)
            elseif spec[1] == 'u32' then v = u32(blob, off)
            else v = rva + spec[3][k] + i32(blob, off) end
            if value and v ~= value then return nil, 'occurrences disagree' end
            value = v
        end
        if spec[1] == 'rip' and not self:in_section(value, false) then return nil, 'global not in a data section' end
        if spec[1] == 'call' and not self:in_section(value, true) then return nil, 'function not in a code section' end
        return value
    end

    -- Reads every field of the found signatures. A signature whose fields don't read becomes missing; a field that
    -- differs between signatures is dropped (nil) and listed in problems.
    function Scanner:resolve()
        local seen = {}
        for _, sig in ipairs(self.sigs) do
            local rva = self.found[sig.name]
            if rva then
                local got = {}
                for name, spec in pairs(sig.fields or {}) do
                    local v, why = self:field_value(sig, rva, spec)
                    if not v then
                        self.missing[sig.name] = string.format('field "%s" %s', name, why)
                        self.found[sig.name] = nil
                        got = nil
                        break
                    end
                    got[name] = v
                end
                for name, v in pairs(got or {}) do
                    if seen[name] ~= nil and seen[name] ~= v then
                        self.problems[#self.problems + 1] = string.format('"%s" differs between signatures', name)
                        seen[name] = false
                    elseif seen[name] == nil then
                        seen[name] = v
                    end
                end
            end
        end
        for name, v in pairs(seen) do self.values[name] = v or nil end
        self.done = true
    end

    -- The address of a found signature's match (plus an offset), or nil.
    function Scanner:address(name, offset)
        local rva = self.found[name]
        return rva and self.base + rva + (offset or 0)
    end

    -- Every missing signature as 'name (reason)', for logs and status files.
    function Scanner:missing_list()
        local out = {}
        for _, sig in ipairs(self.sigs) do
            if self.missing[sig.name] then out[#out + 1] = sig.name .. ' (' .. self.missing[sig.name] .. ')' end
        end
        return out
    end
end
-- END SIGNATURE ENGINE

---------------------------------------------------------------------------------------
-- Configuration

-- Each skip is a Mod Options Menu choice; the value is the index into MODES.
local OPTION_PREFIX = 'alomare.skip_intro_animation.'
local MODES = {'off', 'key', 'auto'}
local MODE_NAMES = {off = 'Off', key = 'Manual', auto = 'Automatic'}
local DEFAULT_CHOICE = 3
-- The hellpod entry is not a cutscene scene: it has no scenes, the mod follows the seat instead.
local FEATURES = {
    {id = 'login', label = 'Log-in ship intro', text = 'login', scenes = {'ship_intro', 'ship_bridge_intro'}},
    {id = 'pod', label = 'Cryo pod transition', text = 'pod', scenes = {'ship_teleporter_arrival'}},
    {id = 'ftl', label = 'FTL transition', text = 'ftl',
     scenes = {'ship_planet_departure', 'ship_planet_arrival', 'ship_teleporter_network_join'}},
    {id = 'hellpod', label = 'Hellpod to loadout', text = 'hellpod', scenes = {}},
}
local BINDING = 'alomare.skip_intro_animation.skip'
local MAP_BINDING = 'alomare.skip_intro_animation.map'  -- Mod Bindings Menu key that closes the map, beside Escape
-- Hellpod entry: on the ship (game state 3), the local Helldiver's seat moving into one of the ship's hellpods. Its
-- seat record (64 bytes): +0 seat collection (the hellpod's entity id), moving byte, target node and deadline (offsets
-- from the code). Then the Hellpod briefing (presenter 14) and its loadout screen (MenuScreenType 11), whose intro
-- phase 1 waits a timer before the UI is built.
local HELLPOD = {ship_state = 3, briefing = 14, screen_type = 11, intro_waiting = 1, record_size = 0x40,
                 max_pods = 16, idle_every = 10, ship_every = 30, max_ahead = 30e6, timeout = 180, briefing_wait = 300}
local TIMEOUT_FRAMES = 1200  -- per scene, for a fast-forward
local CHAIN_FRAMES = 900     -- how long an ended scene waits for a follow-up one (joining a lobby: 15 12 11 15 13)

-- Scene layout: ids around the current one (previous, current, queued); the scene context at manager + 0x60
-- starts with the phase; the clock and timer stamps come from the code.
local SCENE = {context = 0x60, max_id = 64, max_phase = 32}
-- Fast-forward plans: per scene, per phase, the timer check (signature) whose stamp and wait are read from the code.
local WARP_PLANS = {
    ship_intro = {[1] = {sig = 't7p1'}, [2] = {sig = 't7p2'}},
    ship_bridge_intro = {
        [2] = {sig = 't3_2s'}, [3] = {sig = 't3_125'}, [4] = {sig = 't3_175'}, [5] = {sig = 't3_25'},
        [6] = {sig = 't3_1s'}, [7] = {sig = 't3_15'}, [8] = {sig = 't3_1s'}, [9] = {sig = 't3_1s'},
        [10] = {sig = 't3_1s'}, [11] = {sig = 't3_2s'}, [12] = {sig = 't3_2s'},
    },
    ship_teleporter_arrival = {
        [2] = {sig = 't13p2'},
        [3] = {sig = 't13p3', hold_frames = 30},  -- the game places the body
        [4] = {sig = 't13p4'},
    },
    ship_planet_departure = {[3] = {sig = 't12p3'}},
    ship_planet_arrival = {[2] = {sig = 't11p2'}},
    ship_teleporter_network_join = {[3] = {sig = 't15p3'}},
}
local FADE_SCENES = {ship_planet_departure = true, ship_planet_arrival = true}
-- The galactic map: the Hologram menu presenter. Outside it the presenter is looked at every MAP_IDLE frames.
local HOLOGRAM, MAP_IDLE = 15, 10
local ESCAPE_NAMES, VK_ESCAPE = {'esc', 'escape'}, 0x1b

---------------------------------------------------------------------------------------
-- Logging and status

local function open_log(name)
    if loader and type(loader.open_log) == 'function' then
        local ok, f = pcall(loader.open_log, name)
        if ok then return f end
    end
end

local log_file = open_log('ImpatientDiver.log')
local log_lines = 0

local function note(msg)
    if not log_file or log_lines >= 5000 then return end
    log_lines = log_lines + 1
    pcall(function()
        log_file:write(string.format('[f%d t%.1f] %s\n', M.frames, os.clock(), msg))
        log_file:flush()
    end)
end

local function write_status(lines)
    local f = open_log('ImpatientDiver_STATUS.log')
    if not f then return end
    pcall(function()
        f:write(table.concat(lines, '\n') .. '\n')
        f:close()
    end)
end

---------------------------------------------------------------------------------------
-- Texts (mod_text: src/bingus_text.lua and locales/, placed ahead of this script by the build)

local T = mod_text.module
local tr = T.new(mod_text.locales.en, mod_text.locales.bundled, function(message) note('Text: ' .. message) end)

-- Mod Options Menu v1.1+ (version 2) and Mod Bindings Menu v2.1+ (version 3) take texts as functions and call them
-- when their pages open, so the texts follow the game's language; older versions take strings with byte limits,
-- where a translation that does not fit stays English. One function per key, so repeated registrations agree.
local text_functions = {}
local function host_text(host, functions_from, key, bytes)
    if (tonumber(host.version) or 1) >= functions_from then
        local fn = text_functions[key]
        if not fn then fn = function() return tr(key) end; text_functions[key] = fn end
        return fn
    end
    local value = tr(key)
    return #value <= bytes and value or tr.english[key]
end

---------------------------------------------------------------------------------------
-- Native memory

local native = {}

local function init_native()
    -- Declared one by one: another mod may already have declared some of them.
    for _, decl in ipairs({
        'void *GetCurrentProcess(void);',
        'void *GetModuleHandleA(const char *name);',
        'int ReadProcessMemory(void *process, const void *address, void *buffer, size_t size, size_t *read);',
        'int WriteProcessMemory(void *process, void *address, const void *buffer, size_t size, size_t *written);',
    }) do pcall(ffi.cdef, decl) end
    local ok, k32 = pcall(ffi.load, 'kernel32')
    if not ok then return false, 'kernel32 unavailable' end
    native.k32, native.process = k32, k32.GetCurrentProcess()
    local game = k32.GetModuleHandleA('game.dll')
    if game == nil then return false, 'game.dll not loaded' end
    native.base = tonumber(ffi.cast('uint64_t', game))
    return true
end

local function read(address, size)
    local buf, got = ffi.new('uint8_t[?]', size), ffi.new('size_t[1]')
    if native.k32.ReadProcessMemory(native.process, ffi.cast('const void *', address), buf, size, got) == 0
       or tonumber(got[0]) ~= size then
        return nil
    end
    return ffi.string(buf, size)
end

local function write(address, bytes)
    local got = ffi.new('size_t[1]')
    local ok = native.k32.WriteProcessMemory(native.process, ffi.cast('void *', address), bytes, #bytes, got)
    return ok ~= 0 and tonumber(got[0]) == #bytes
end

local function u32(blob, offset)
    offset = offset or 0
    if not blob or #blob < offset + 4 then return nil end
    local v = ffi.new('uint32_t[1]')
    ffi.copy(v, blob:sub(offset + 1, offset + 4), 4)
    return tonumber(v[0])
end

local function i32(blob, offset)
    local v = u32(blob, offset)
    if v and v >= 2147483648 then v = v - 4294967296 end
    return v
end

local function u64(blob)
    if not blob or #blob ~= 8 then return nil end
    local v = ffi.new('uint64_t[1]')
    ffi.copy(v, blob, 8)
    return v[0]
end

local function pointer(blob)
    local v = u64(blob)
    if not v then return nil end
    local a = tonumber(v)
    if a < 0x10000 or a >= 0x800000000000 then return nil end
    return a
end

local ZERO32 = string.rep('\0', 4)

---------------------------------------------------------------------------------------
-- Resolution: signatures -> what each feature can use

local code = nil  -- the signature engine
local V = {}      -- values read from the matched code (offsets, waits; globals as rvas)
local derived = {}  -- manager/clock/fader globals (rva), scene ids by name

-- Reads the scene names from the id-to-name switch at rva (pure reads); nil if it isn't that switch.
local function scene_names(rva)
    local head = read(native.base + rva, 30)
    if not head then return nil end
    local count = head:byte(5) + 1
    local table_rva = u32(head, 21)
    local image_disp = i32(head, 14)
    if count > SCENE.max_id or not table_rva or not image_disp or rva + 18 + image_disp ~= 0 then return nil end
    local jumps = read(native.base + table_rva, count * 4)
    if not jumps then return nil end
    local ids = {}
    for id = 1, count do
        local at = u32(jumps, (id - 1) * 4)
        local lea = at and read(native.base + at, 8)
        if not lea or lea:sub(1, 3) ~= '\x48\x8d\x05' or lea:byte(8) ~= 0xc3 then return nil end
        local text = read(native.base + at + 7 + i32(lea, 3), 48)
        local name = text and text:match('^([%w_]+)%z')
        if not name then return nil end
        ids[name] = id
    end
    return ids
end

local state = {ready = false, started = false, menu = nil, scene_feature = {}, plans = {}, map = {}}

local function derive()
    for k, v in pairs(code.values) do V[k] = v end
    if code.found.interrupt_site then derived.manager = V.manager end
    if code.found.t13p2 then derived.clock = V.clock end
    if code.found.fader then derived.fader = V.fader end
    if code.found.names then derived.scene_ids = scene_names(code.found.names) end
    if code.found.names and not derived.scene_ids then note('Scene name table not recognized') end
    if code.found.game_state then derived.game = V.game end
end

-- The galactic map exit: usable when the presenter manager, its close requests and the Hologram request are known.
local function map_usable()
    for _, name in ipairs({'presenters', 'presenter_open', 'presenter_update', 'hologram_request'}) do
        if not code.found[name] then return false, 'code "' .. name .. '" ' .. (code.missing[name] or 'not found') end
    end
    for _, k in ipairs({'ui', 'presenters', 'depth', 'current_presenter', 'collection', 'holo_slot', 'close_flag'}) do
        if not V[k] then return false, 'value "' .. k .. '" unavailable' end
    end
    -- The Hologram case must be inside the close-request check the update calls.
    local at = code.found.hologram_request
    if not V.check or at < V.check or at > V.check + 0x400 then return false, 'the close-request check moved' end
    return true
end

-- The hellpod entry: usable when the local Helldiver, its seat record, the ship's hellpods and the game state are
-- known. The briefing intro part also needs the presenter manager and the loadout screen (else only the seat).
local function hellpod_usable()
    for _, name in ipairs({'local_ref', 'ref_resolver', 'seaters', 'seat_wait', 'hellpods', 'game_state'}) do
        if not code.found[name] then return false, 'code "' .. name .. '" ' .. (code.missing[name] or 'not found') end
    end
    -- The avatar lookup must call the resolver found (its body starts 4 bytes in, after `sub rsp, 8`).
    if V.resolver ~= code.found.ref_resolver - 4 then return false, 'the avatar lookup calls another resolver' end
    local found = {'seat transition'}
    state.hellpod_intro = (code.found.screen and code.found.briefing_intro and code.found.presenters
                           and code.found.presenter_open and V.ui and V.presenters and V.current_presenter) and true
                          or false
    if state.hellpod_intro then found[#found + 1] = 'briefing intro' end
    return true, '', found
end

-- Writes the status file from the current modes and, once resolved, what each feature can use.
local function report()
    if not state.ready then return end  -- still resolving (the map exit is always on); finish_resolution reports
    local lines, working, broken = {}, 0, 0
    for _, feature in ipairs(FEATURES) do
        local text
        if feature.mode == 'off' then
            text = feature.label .. ': Off'
        elseif feature.usable then
            working = working + 1
            text = string.format('%s: %s (%s)', feature.label, MODE_NAMES[feature.mode], table.concat(feature.found, ', '))
        else
            broken = broken + 1
            text = feature.label .. ': NOT AVAILABLE, plays normally (' .. feature.why .. ')'
        end
        lines[#lines + 1] = text
    end
    local map = state.map
    if map.usable then
        working = working + 1
        lines[#lines + 1] = 'Galactic map quick exit: On (Escape or the Mod Bindings Menu key closes the map from any '
                            .. 'level)'
    else
        broken = broken + 1
        lines[#lines + 1] = 'Galactic map quick exit: NOT AVAILABLE, the map works as normal (' .. tostring(map.why) .. ')'
    end
    local verdict
    if broken > 0 then
        verdict = 'PARTIAL - ' .. broken .. ' selected feature(s) not available after a game update; those work as normal'
    elseif working > 0 then
        verdict = 'OK - ' .. working .. ' feature(s) active'
    else
        verdict = 'IDLE - every feature is set to Off'
    end
    table.insert(lines, 1, verdict)
    table.insert(lines, 2, 'Impatient Diver ' .. M.version)
    table.insert(lines, 3, state.menu and 'Settings: Mod Options Menu (escape menu > MODS > Impatient Diver)'
                           or 'Settings: defaults, every feature on (Mod Options Menu not found)')
    if code and #code.moved > 0 then
        lines[#lines + 1] = 'Signatures were searched for (game updated since build 25480438).'
    end
    write_status(lines)
    note(verdict)
end

-- Decides, per feature and scene, what is usable, and writes the status file.
local function finish_resolution()
    derive()
    local ids = derived.scene_ids
    local core = derived.manager and ids and V.current
    for _, feature in ipairs(FEATURES) do
        local usable, why = core, core and '' or 'cutscene system not found'
        if usable and not (derived.clock and V.clock_now) then usable, why = false, 'scene clock not found' end
        local scenes = {}
        if feature.id == 'hellpod' then
            usable, why, scenes = hellpod_usable()
            scenes = scenes or {}
        elseif usable then
            for _, scene in ipairs(feature.scenes) do
                local id = ids[scene]
                local ok = id ~= nil
                if ok then
                    local plan = {}
                    for phase, step in pairs(WARP_PLANS[scene]) do
                        local entry = {hold_frames = step.hold_frames}
                        if step.sig then
                            entry.stamp, entry.wait = V[step.sig .. '_stamp'], V[step.sig .. '_wait']
                            if not code.found[step.sig] or not entry.stamp or not entry.wait then ok = false; break end
                        end
                        plan[phase] = entry
                    end
                    if ok then state.plans[id] = plan end
                end
                if ok then
                    state.scene_feature[id] = {feature = feature, name = scene}
                    scenes[#scenes + 1] = scene
                end
            end
            if #scenes == 0 then usable, why = false, 'its scenes were not found' end
        end
        if not usable then
            for _, scene in ipairs(feature.scenes) do
                local id = ids and ids[scene]
                if id then state.scene_feature[id], state.plans[id] = nil, nil end
            end
        end
        feature.usable, feature.why, feature.found = usable and true or false, why, scenes
        note(feature.label .. ': ' .. (usable and table.concat(scenes, ', ') or 'not available (' .. why .. ')'))
    end
    state.map.usable, state.map.why = map_usable()
    note('Galactic map quick exit: ' .. (state.map.usable and 'available' or ('not available (' .. state.map.why .. ')')))
    for _, line in ipairs(code:missing_list()) do note('Signature ' .. line) end
    for _, line in ipairs(code.problems) do note('Signature problem: ' .. line) end
    state.fader = derived.fader
    state.names = {}
    for name, id in pairs(ids or {}) do state.names[id] = name end
    state.ready = true
    report()
end

---------------------------------------------------------------------------------------
-- Scene state

local function manager()
    return derived.manager and pointer(read(native.base + derived.manager, 8))
end

-- current scene id and phase, or nil
local function scene_now(mgr)
    local current = mgr and u32(read(mgr + V.current, 4))
    if not current or current > SCENE.max_id then return nil end
    local phase = current ~= 0 and u32(read(mgr + SCENE.context, 4)) or 0
    if not phase or phase > SCENE.max_phase then return nil end
    return current, phase
end

local function clock_now()
    local clock = derived.clock and pointer(read(native.base + derived.clock, 8))
    local now = clock and u64(read(clock + V.clock_now, 8))
    if now and now ~= 0 then return now end
end

-- The presenter manager (UI state + presenters), or nil.
local function presenter_manager()
    local ui = V.ui and pointer(read(native.base + V.ui, 8))
    return ui and ui + V.presenters
end

local function hold_fade_clear()
    local base = state.fader and pointer(read(native.base + state.fader, 8))
    local fader = base and base + V.fader_offset
    local alpha, target = fader and u32(read(fader + V.fader_alpha, 4)), fader and u32(read(fader + V.fader_target, 4))
    if not alpha or not target or (alpha == 0 and target == 0) then return end
    local _ = write(fader + V.fader_duration, ZERO32) and write(fader + V.fader_alpha, ZERO32)
              and write(fader + V.fader_start, ZERO32) and write(fader + V.fader_target, ZERO32)
end

---------------------------------------------------------------------------------------
-- Skips

local run = {warp = nil, scene = nil, since = 0}

-- Fast-forward: each frame, moves the timed phase's stamp back so the game's own update sees the wait as
-- over. Follows the scene chain; stops when an unskippable scene starts, when a phase with a step doesn't move on in
-- time, or if a timer looks wrong. Phases without a step (loading, other players) are left to the game. by_key:
-- started by a key press (then Manual scenes are followed too).
local function warp_step(mgr, current, phase)
    local w = run.warp
    local function stop(why) note('Fast-forward ' .. why); run.warp = nil end
    if current == 0 then
        w.idle_since = w.idle_since or M.frames
        if M.frames > w.idle_since + CHAIN_FRAMES then stop('ended') end
        return
    end
    local owner = state.scene_feature[current]
    local plan = state.plans[current]
    local mode = owner and owner.feature.mode
    if not plan or not owner or mode == 'off' or (mode ~= 'auto' and not w.by_key) then return stop('ended') end
    w.idle_since = nil
    if current ~= w.scene or phase ~= w.phase then
        if current ~= w.scene then note('Fast-forwarding ' .. owner.name) end
        w.scene, w.phase, w.since = current, phase, M.frames
        w.deadline = M.frames + TIMEOUT_FRAMES
    end
    if FADE_SCENES[owner.name] then hold_fade_clear() end
    local step = plan[phase]
    if not step then return end
    if M.frames > w.deadline then return stop('timed out (' .. owner.name .. ' phase ' .. phase .. ')') end
    if step.hold_frames and M.frames < w.since + step.hold_frames then return end
    if step.stamp then
        local now = clock_now()
        local address = mgr + SCENE.context + step.stamp
        local stamp = u64(read(address, 8))
        if not now or not stamp then return stop('stopped: timer unreadable') end
        if stamp > now then return stop('stopped: timer ahead of the clock') end
        if now - stamp < step.wait then
            if not write(address, ffi.string(ffi.new('uint64_t[1]', now - step.wait), 8)) then
                return stop('stopped: write failed')
            end
            return  -- due now; the game changes phase itself
        end
    end
end

---------------------------------------------------------------------------------------
-- Keys: spacebar for the skips (raw keyboard, plus an optional Mod Bindings Menu binding), Escape for the map

local key = {space = nil, space_down = false, menu = nil, menu_down = false, registered = false, wanted = false,
             escape = nil, escape_down = false, map_registered = false, map_down = false}

-- Whether a Stingray keyboard button went down this frame (`field` keeps its id and state in `key`).
local function keyboard_edge(id_field, down_field)
    local keyboard = S and S.Keyboard
    if not (keyboard and type(keyboard.pressed) == 'function' and key[id_field]) then return false end
    local ok, down = pcall(keyboard.pressed, key[id_field])
    down = ok and down and true or false
    local edge = down and not key[down_field]
    key[down_field] = down
    return edge
end

local function poll_key()
    local pressed = false
    local keyboard = S and S.Keyboard
    if key.space == nil then
        local ok, id = false, nil
        if keyboard and type(keyboard.button_id) == 'function' then ok, id = pcall(keyboard.button_id, 'space') end
        key.space = ok and id or false
    end
    if keyboard_edge('space', 'space_down') then pressed = true end
    local menu = rawget(_G, 'ModBindingsMenu')
    if menu and menu.api == 1 then
        if not key.registered then
            key.registered = true
            local ok, res = pcall(menu.register_binding, BINDING, host_text(menu, 3, 'binding.skip', 64), nil,
                                  {category = host_text(menu, 3, 'option.mod', 64)})
            note('Mod Bindings Menu binding: ' .. ((ok and res) and 'registered' or 'not registered'))
        end
        local ok, down = pcall(menu.is_down, BINDING)
        down = ok and down and true or false
        if down and not key.menu_down then pressed = true end
        key.menu_down = down
    end
    return pressed
end

-- Escape: the engine's keyboard (the first name it knows), else the Windows key state while the game has focus.
local win = nil
local function escape_pressed()
    if key.escape == nil then
        local keyboard = S and S.Keyboard
        key.escape = false
        if keyboard and type(keyboard.button_id) == 'function' then
            for _, name in ipairs(ESCAPE_NAMES) do
                local ok, id = pcall(keyboard.button_id, name)
                if ok and id then key.escape = id; note('Escape key: engine button "' .. name .. '"'); break end
            end
        end
        if not key.escape then note('Escape key: Windows key state') end
    end
    if key.escape then return keyboard_edge('escape', 'escape_down') end
    if win == nil then
        win = false
        pcall(function()
            for _, decl in ipairs({'short GetAsyncKeyState(int key);', 'void *GetForegroundWindow(void);',
                                   'unsigned int GetWindowThreadProcessId(void *window, unsigned int *process);',
                                   'unsigned int GetCurrentProcessId(void);'}) do pcall(ffi.cdef, decl) end
            win = {user32 = ffi.load('user32'), pid = ffi.new('unsigned int[1]')}
            win.own = tonumber(native.k32.GetCurrentProcessId())
        end)
    end
    if not win then return false end
    local window = win.user32.GetForegroundWindow()
    local focused = window ~= nil and (win.user32.GetWindowThreadProcessId(window, win.pid) or true)
                    and tonumber(win.pid[0]) == win.own
    local down = focused and win.user32.GetAsyncKeyState(VK_ESCAPE) < 0 or false
    local edge = down and not key.escape_down
    key.escape_down = down
    return edge
end

-- The Mod Bindings Menu key that closes the galactic map (registered once that mod is there, whatever the skip modes):
-- whether it went down this frame.
local function map_binding_pressed()
    local menu = rawget(_G, 'ModBindingsMenu')
    if not (menu and menu.api == 1) then return false end
    if not key.map_registered then
        key.map_registered = true
        local ok, res = pcall(menu.register_binding, MAP_BINDING, host_text(menu, 3, 'binding.map', 64), nil,
                              {category = host_text(menu, 3, 'option.mod', 64)})
        note('Mod Bindings Menu map binding: ' .. ((ok and res) and 'registered' or 'not registered'))
    end
    local ok, down = pcall(menu.is_down, MAP_BINDING)
    down = ok and down and true or false
    local edge = down and not key.map_down
    key.map_down = down
    return edge
end

---------------------------------------------------------------------------------------
-- Galactic Map Quick Exit

local function map_step()
    local map = state.map
    -- The binding is registered (and its state followed) every frame, so a press made before the map opens is seen
    -- as held, not as a new press.
    local binding = map_binding_pressed()
    if not map.usable then return end
    if not map.open and M.frames % MAP_IDLE ~= 0 then return end
    local mgr = presenter_manager()
    local current = mgr and u32(read(mgr + V.current_presenter, 4))
    if current ~= HOLOGRAM then
        if map.open then map.open = false; note('Galactic map closed') end
        key.escape_down = false
        return
    end
    if not map.open then
        map.open = true
        escape_pressed()  -- the press that opened a menu over it doesn't count
        note('Galactic map open')
        return
    end
    local escape = escape_pressed()
    if not (escape or binding) then return end
    -- The Hologram presenter's close request, as the presenter manager's update reads it: the game closes the map
    -- (and pops its screen) itself. The object is read fresh: it only exists while the map is open.
    local request = pointer(read(mgr + V.collection + V.holo_slot, 8))
    local by = escape and 'Escape' or 'Map binding'
    if request and write(request + V.close_flag, '\1') then
        note(by .. ' on the galactic map: close requested')
    else
        note(by .. ' on the galactic map: close request unavailable')
    end
end

---------------------------------------------------------------------------------------
-- Hellpod entry: the seat transition into the hellpod, then the Hellpod briefing's intro wait

-- A value in one of the game's hashed maps ({key u32, value u32} buckets, a power-of-two capacity, an empty key and a
-- multiplier; the probe starts at key * multiplier), or nil. object + the offsets read from the code.
local function lookup(object, at, k)
    local buckets = pointer(read(object + at.map, 8))
    local capacity, empty = u32(read(object + at.capacity, 4)), u32(read(object + at.empty, 4))
    local multiplier = u32(read(object + at.multiplier, 4))
    if not (buckets and capacity and empty and multiplier) or capacity < 1 or capacity > 0x100000 then return nil end
    local power = 1
    while power < capacity do power = power * 2 end
    if power ~= capacity then return nil end
    local hash = tonumber(ffi.cast('uint32_t', ffi.new('uint64_t', multiplier) * k))
    for probe = 0, math.min(capacity, 128) - 1 do
        local entry = read(buckets + ((hash + probe) % capacity) * 8, 8)
        local found = u32(entry, 0)
        if not found or found == empty then return nil end
        if found == k then return u32(entry, 4) end
    end
end

-- The local Helldiver's entity id (the player manager's avatar reference, through the game's resolver), or nil.
local function local_avatar()
    local players = pointer(read(native.base + V.players, 8))
    if not players or u32(read(players + V.local_active, 4)) == 0 then return nil end
    local ref = u32(read(players + V.avatar_ref, 4))
    if not ref or ref == 0x7fff then return nil end
    local entities = pointer(read(native.base + V.entities, 8))
    local index = entities and lookup(entities, {map = V.ent_map, capacity = V.ent_capacity, empty = V.ent_empty,
                                                 multiplier = V.ent_multiplier}, ref)
    if not index or index >= 0x1000000 then return nil end
    local id = u32(read(entities + V.ent_ids * 8 + index * 24, 4))
    if not id or id == 0 or id == 0xffffffff then return nil end
    return id
end

-- The seat record of an entity (a Helldiver), or nil.
local function seat_record(id)
    local seaters = pointer(read(native.base + V.seaters, 8))
    local index = seaters and lookup(seaters, {map = V.seat_map, capacity = V.seat_capacity, empty = V.seat_empty,
                                               multiplier = V.seat_multiplier}, id)
    if not index or index >= 0x100000 then return nil end
    local records = pointer(read(seaters + V.seat_records, 8))
    return records and records + index * HELLPOD.record_size
end

-- A seat record's state: the seat collection (entity id) it is in or entering, whether it is moving, and the
-- current step's deadline (u64 microseconds), or nil.
local function seat_state(record)
    local r = read(record, HELLPOD.record_size)
    if not r then return nil end
    return {collection = u32(r, 0), moving = r:byte(V.seat_moving + 1) ~= 0, target = i32(r, V.seat_target),
            deadline = u64(r:sub(V.seat_deadline + 1, V.seat_deadline + 8))}
end

local function seat_clock()
    local clock = pointer(read(native.base + V.seat_clock, 8))
    local now = clock and u64(read(clock + V.seat_clock_now, 8))
    if now and now ~= 0 then return now end
end

-- Whether an entity id is one of the ship's hellpods (the hellpod manager's count at +8, each entity's id at +8).
local function is_hellpod(id)
    local pods = pointer(read(native.base + V.hellpods, 8))
    local count = pods and u32(read(pods + 8, 4))
    if not count or count > HELLPOD.max_pods then return false end
    for i = 0, count - 1 do
        local pod = pointer(read(pods + V.pod_list + i * 8, 8))
        if pod and u32(read(pod + 8, 4)) == id then return true end
    end
    return false
end

local function game_state()
    local game = derived.game and pointer(read(native.base + derived.game, 8))
    return game and u32(read(game + V.game_state, 4))
end

-- The open Hellpod loadout screen while the Hellpod briefing is the current menu, or nil.
local function briefing_screen()
    local pm = presenter_manager()
    if not pm or u32(read(pm + V.current_presenter, 4)) ~= HELLPOD.briefing then return nil end
    local stack = pointer(read(native.base + V.screen_stack, 8))
    if not stack or u32(read(stack, 4)) ~= HELLPOD.screen_type then return nil end
    return pointer(read(stack + V.screen_slot, 8))
end

-- idle: watching the local seat (every few frames, on the ship only); armed (Manual): an entry started, waiting for
-- the skip key; seat: moving each step's deadline to now until the seat is reached (the game then opens the
-- briefing itself); briefing: waiting for the briefing's intro wait, then expiring its timer.
local entry = {phase = 'idle', record = nil, resolved = -1e9, collection = nil}
local hellpod_feature = nil

local function entry_stop(why)
    note('Hellpod entry: ' .. why)
    entry.phase = 'idle'
end

local function hellpod_step(pressed)
    local feature = hellpod_feature
    if not (feature and feature.usable) or feature.mode == 'off' then entry.phase = 'idle'; return end
    if entry.phase == 'idle' and M.frames % HELLPOD.idle_every ~= 0 then return end
    if entry.phase == 'idle' and game_state() ~= HELLPOD.ship_state then
        entry.collection, entry.record = nil, nil  -- off the ship: forget the seat (it is looked up again on board)
        return
    end
    if not entry.record or M.frames - entry.resolved > 300 then
        local avatar = local_avatar()
        entry.record, entry.resolved = avatar and seat_record(avatar), M.frames
    end
    local s = entry.record and seat_state(entry.record)
    if not s then entry.record = nil; return end
    local previous = entry.collection
    entry.collection = s.collection
    if entry.phase == 'idle' then
        -- An entry: the seat was free and now moves into one of the ship's hellpods.
        if previous ~= 0 or not s.collection or s.collection == 0 or not s.moving or not is_hellpod(s.collection) then
            return
        end
        entry.pod, entry.since = s.collection, M.frames
        if feature.mode == 'auto' then
            entry.phase = 'seat'
            note('Hellpod entry: skip started (automatic)')
        else
            entry.phase = 'armed'
            note('Hellpod entry: started (waiting for the skip key)')
        end
        return
    end
    if entry.phase == 'armed' then
        if pressed then
            entry.phase, entry.since = s.moving and 'seat' or 'briefing', M.frames
            note('Hellpod entry: skip started (key press)')
        elseif M.frames > entry.since + HELLPOD.briefing_wait then
            entry.phase = 'idle'
        end
        return
    end
    if entry.phase == 'seat' then
        if not s.moving or s.collection ~= entry.pod then
            note(string.format('Hellpod entry: seat reached after %d frames', M.frames - entry.since))
            entry.phase, entry.since = 'briefing', M.frames
            if not state.hellpod_intro then entry_stop('done (briefing intro skip unavailable)') end
            return
        end
        if M.frames > entry.since + HELLPOD.timeout then return entry_stop('stopped: the seat was not reached in time') end
        local now = seat_clock()
        if not now or not s.deadline then return entry_stop('stopped: clock unreadable') end
        if s.deadline > now then
            if s.deadline - now > HELLPOD.max_ahead then return entry_stop('stopped: deadline too far ahead') end
            if not write(entry.record + V.seat_deadline, ffi.string(ffi.new('uint64_t[1]', now), 8)) then
                return entry_stop('stopped: write failed')
            end
        end
        return
    end
    if entry.phase == 'briefing' then
        if not state.hellpod_intro then return entry_stop('done (briefing intro skip unavailable)') end
        local screen = briefing_screen()
        local intro = screen and u32(read(screen + V.intro_phase, 4))
        if intro == HELLPOD.intro_waiting then
            if write(screen + V.intro_timer, ZERO32) then
                entry_stop(string.format('briefing intro skipped (%d frames after the seat)', M.frames - entry.since))
            else
                entry_stop('briefing intro: write failed')
            end
        elseif M.frames > entry.since + HELLPOD.briefing_wait then
            entry_stop('briefing intro not seen')
        end
    end
end

---------------------------------------------------------------------------------------
-- Frame step

local function step()
    if not state.ready then
        if code.scan and code:step() then finish_resolution() end
        return
    end
    map_step()
    if not state.skips_on and not run.warp then return end  -- only the map exit is on: no scene polling
    local pressed = key.wanted and poll_key()
    -- The hellpod entry is not a cutscene scene: it follows the local seat (a press that starts it is used up).
    local armed = entry.phase == 'armed'
    hellpod_step(pressed)
    if armed and entry.phase ~= 'armed' and entry.phase ~= 'idle' then pressed = false end
    local mgr = manager()
    if not mgr then return end
    local current, phase = scene_now(mgr)
    if not current then return end

    if current ~= run.scene then
        run.scene, run.since = current, M.frames
        note('Scene ' .. (current == 0 and 'none' or (state.names[current] or tostring(current))))
    end
    local owner = current ~= 0 and state.scene_feature[current]
    if owner and not run.warp then
        local mode = owner.feature.mode
        local go = (mode == 'auto' and run.auto_done ~= run.since) or (mode == 'key' and pressed)
        if go then
            if mode == 'auto' then run.auto_done = run.since end  -- once per scene instance
            local why = mode == 'auto' and 'automatic' or 'key press'
            run.warp = {by_key = mode == 'key'}
            note('Skip started (' .. why .. ')')
        end
    end
    if run.warp then warp_step(mgr, current, phase) end
end

-- Native access and signatures, resolved on the first frame (the map exit is always on).
local function start()
    state.started = true
    local ok, why = init_native()
    if not ok then
        write_status({'NOT AVAILABLE - ' .. why .. '; everything works as normal', 'Impatient Diver ' .. M.version})
        note('Native access unavailable: ' .. why)
        M.retired = true
        return
    end
    -- The game's Text Language, for this mod's texts and every other mod's (bingus_text's shared registry).
    local tag, game_code = T.observe(read, native.base)
    note('Text language: ' .. tostring(T.language()) .. ' (game setting ' .. tostring(game_code or 'unreadable')
         .. ', tag ' .. tostring(tag) .. ')')
    -- A scene-name switch only counts if it decodes to the scene names (a decoy switch elsewhere doesn't).
    code = sigscan.new(SIGS, read, native.base, {
        names = function(rva) local ids = scene_names(rva); return ids and ids.ship_teleporter_arrival ~= nil end})
    local all, reason = code:start()
    if all == nil then
        write_status({'NOT AVAILABLE - ' .. reason .. '; everything works as normal', 'Impatient Diver ' .. M.version})
        M.retired = true
    elseif all then
        finish_resolution()
    else
        note('Searching game.dll for moved code (game updated?)')
    end
end

---------------------------------------------------------------------------------------
-- Settings: Mod Options Menu, which may load before or after this addon. Without it, each skip takes its default.

for _, feature in ipairs(FEATURES) do
    feature.default = feature.default or DEFAULT_CHOICE
    feature.mode = MODES[feature.default]
    if feature.mode == 'key' then key.wanted = true end
    if feature.id == 'hellpod' then hellpod_feature = feature end
end
state.skips_on = true  -- the map exit is always on, so native access always starts

local function modes_changed()
    key.wanted, state.skips_on = false, false
    for _, feature in ipairs(FEATURES) do
        if feature.mode == 'key' then key.wanted = true end
        if feature.mode ~= 'off' then state.skips_on = true end
    end
    report()
end

local function set_mode(feature, value)  -- true if the mode changed
    local mode = MODES[value] or MODES[feature.default]
    if feature.mode == mode then return false end
    note(feature.label .. ' set to ' .. MODE_NAMES[mode])
    feature.mode = mode
    return true
end


local function connect_menu()
    local menu = rawget(_G, 'ModOptionsMenu')
    if type(menu) ~= 'table' or menu.api ~= 1 then return false end
    state.menu = menu
    local mod = host_text(menu, 2, 'option.mod', 40)
    -- OFF is shown in the game's own translation when passed as plain English.
    local choices = {'Off', host_text(menu, 2, 'option.choice.manual', 48), host_text(menu, 2, 'option.choice.automatic', 48)}
    for _, feature in ipairs(FEATURES) do
        local id = OPTION_PREFIX .. feature.id
        local ok, done, why = pcall(menu.register_option, id, {
            type = 'choice', label = host_text(menu, 2, 'option.' .. feature.text .. '.label', 64), mod = mod,
            choices = choices, default = feature.default,
            description = host_text(menu, 2, 'option.' .. feature.text .. '.description', 400)})
        if ok and done then
            pcall(menu.on_change, id, function(value)
                if set_mode(feature, value) then modes_changed() end
            end)
            local got, value = pcall(menu.get, id)
            set_mode(feature, got and value)
        else
            note('Option ' .. id .. ' not registered: ' .. tostring(ok and why or done))
        end
    end
    note('Mod Options Menu connected (version ' .. tostring(menu.version or 1) .. ')')
    return true
end

---------------------------------------------------------------------------------------
-- Frame hook

local function frame()
    M.frames = M.frames + 1
    if not state.menu and connect_menu() then modes_changed() end
    if state.started then
        step()
    else
        start()  -- the map exit is always on
    end
end

local original_update = rawget(_G, 'update')
update = function(dt, ...)
    if not M.retired then
        local ok, err = xpcall(frame, debug.traceback)
        if not ok then
            M.errors = M.errors + 1
            note('Error: ' .. tostring(err))
            if M.errors >= 5 then
                M.retired = true
                write_status({'STOPPED - repeated errors; everything works as normal (see ImpatientDiver.log)',
                              'Impatient Diver ' .. M.version})
            end
        end
    end
    if type(original_update) == 'function' then return original_update(dt, ...) end
end

note('Impatient Diver ' .. M.version .. ' loaded')
M._test = {state = state, values = V, derived = derived, run = run, code = function() return code end,
           features = FEATURES}  -- offline tests
return M
